# Hello World example for DTU biosustain and DTU bioengineering Data Club

name: Hello World example

on:
  push:

jobs:
  say-hello-world:
    runs-on: ubuntu-latest
    steps:
    - name: biosustain
      run: echo "Hello DTU biosustain!"
    - name: bioengineering
      run: echo "Hello DTU bioengineering!"
  cowsay-job:
    runs-on:  ubuntu-latest
    steps:
    - name: install_cowsay
      run: pip install cowsay
    - name: use_cowsay
      run: cowsay -c cheese -t 'hey there'
  cowpy-job:
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: install_cowpy
      run: pip install cowpy
    - name: use_cowpy
      run: cowpy -c tux hey there
  cowpy-from_py:
    runs-on:  ubuntu-latest
    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: install_cowpy
      run: pip install cowpy
    - name: medium_exercise
      run: python3 medium_exercise.py .

